<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Antonia CEA, Eva Carolina Kennedy">

<title>Trabajo final estadística</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Trabajo final estadística CEA_KENNEDY_files/libs/clipboard/clipboard.min.js"></script>
<script src="Trabajo final estadística CEA_KENNEDY_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Trabajo final estadística CEA_KENNEDY_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Trabajo final estadística CEA_KENNEDY_files/libs/quarto-html/popper.min.js"></script>
<script src="Trabajo final estadística CEA_KENNEDY_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Trabajo final estadística CEA_KENNEDY_files/libs/quarto-html/anchor.min.js"></script>
<link href="Trabajo final estadística CEA_KENNEDY_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Trabajo final estadística CEA_KENNEDY_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Trabajo final estadística CEA_KENNEDY_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Trabajo final estadística CEA_KENNEDY_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Trabajo final estadística CEA_KENNEDY_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo final estadística</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Antonia CEA, Eva Carolina Kennedy </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="religiosidad-y-apoyo-a-gobiernos-autoritarios" class="level1">
<h1>Religiosidad y apoyo a gobiernos autoritarios</h1>
<section id="un-análisis-de-la-encuesta-social-longitudinal-de-chile-elsoc" class="level3">
<h3 class="anchored" data-anchor-id="un-análisis-de-la-encuesta-social-longitudinal-de-chile-elsoc"><em>Un análisis de la Encuesta Social Longitudinal de Chile (ELSOC)</em></h3>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
</section>
<section id="introducción" class="level3">
<h3 class="anchored" data-anchor-id="introducción">Introducción</h3>
<p>El presente trabajo aborda el fenómeno del apoyo a gobiernos autoritarios en las sociedades democráticas y su posible relación con la religiosidad. En las últimas décadas, el estudio del autoritarismo ha cobrado renovada importancia debido al resurgimiento de liderazgos y discursos que privilegian el orden, la obediencia y las jerarquías tradicionales. El interés por comprender este fenómeno tiene sus orígenes en los trabajos pioneros de Adorno y sus colaboradores (1950), quienes buscaron explicar las predisposiciones individuales y sociales que favorecían la adhesión a ideologías y regímenes autoritarios tras la Segunda Guerra Mundial. A partir de estos aportes, el estudio del autoritarismo evolucionó hacia nuevas perspectivas que ampliaron la comprensión de los factores sociales y culturales asociados a estas actitudes, entre ellos la religiosidad.</p>
<p>Dentro de estos factores, la religiosidad ha ocupado un lugar relevante en la literatura, debido a que distintas investigaciones han planteado que determinadas formas de participación religiosa podrían asociarse con una mayor adhesión a valores de obediencia, convencionalismo y respeto por la autoridad. No obstante, la evidencia sobre esta relación no ha sido concluyente, por lo que continúa siendo un tema de interés para la investigación en ciencias sociales. En este sentido, profundizar en esta asociación contribuye a comprender las dinámicas sociales que influyen en la legitimación de determinadas formas de autoridad y en el funcionamiento de las democracias contemporáneas.</p>
<p>En la presente investigación se analizarán los factores que podrían influir en el apoyo a gobiernos autoritarios en Chile, centrándose particularmente en el papel de la religiosidad como un posible factor asociado a una mayor o menor disposición a respaldar este tipo de regímenes.</p>
<section id="marco-teórico" class="level4">
<h4 class="anchored" data-anchor-id="marco-teórico"><strong>Marco teórico</strong></h4>
<p>La propuesta de Altemeyer (1981) representa uno de los principales desarrollos contemporáneos en el estudio del autoritarismo. En ella, el autor desarrolla el concepto de <strong>Autoritarismo de Derecha</strong> (<em>Right-Wing Authoritarianism</em>, RWA), definido como una orientación actitudinal compuesta por tres dimensiones fundamentales: la <strong>sumisión autoritaria</strong>, entendida como la disposición a obedecer a las autoridades consideradas legítimas; la <strong>agresión autoritaria</strong>, que implica el apoyo a sanciones dirigidas hacia quienes desafían el orden establecido; y el <strong>convencionalismo</strong>, referido a la adhesión a normas y valores tradicionales. Desde esta perspectiva, las personas con mayores niveles de autoritarismo tenderían a mostrar una mayor predisposición a respaldar formas de autoridad fuertes y, en determinados contextos, a manifestar una mayor aceptación hacia gobiernos autoritarios.</p>
<p>La literatura sobre autoritarismo ha examinado diversos factores que podrían contribuir a explicar la adhesión a este tipo de actitudes, entre ellos la religiosidad. Para comprender esta posible asociación, resulta necesario definir este concepto desde una perspectiva sociológica. Glock (1962) concibe la religiosidad como un constructo multidimensional que no puede reducirse únicamente a las creencias religiosas, sino que también comprende las prácticas, las experiencias, el conocimiento religioso y las consecuencias que la religión tiene en la vida de los individuos. Dentro de estas dimensiones, la práctica religiosa constituye una manifestación observable del compromiso religioso, expresada, entre otros aspectos, mediante la participación en actividades religiosas como la asistencia a servicios religiosos. En consecuencia, la frecuencia de asistencia a estos servicios representa un indicador ampliamente utilizado para aproximarse empíricamente a la dimensión práctica o ritual de la religiosidad.</p>
<p>Sobre esta base, diversos estudios comenzaron a examinar la relación entre la religiosidad y el autoritarismo. En particular, Altemeyer y Hunsberger (1992) analizaron esta asociación a partir del modelo de <strong>Autoritarismo de Derecha</strong> (<em>Right-Wing Authoritarianism</em>, RWA), incorporando indicadores de participación religiosa, entre ellos la frecuencia de asistencia a servicios religiosos. Sus resultados mostraron que este indicador presentaba una asociación positiva con el RWA, sugiriendo que determinadas expresiones de la religiosidad podrían vincularse con una mayor valoración de la obediencia, el convencionalismo y el respeto por la autoridad. Estos hallazgos constituyen un antecedente teórico y empírico para analizar si la religiosidad también se asocia con una mayor probabilidad de apoyar gobiernos autoritarios en el contexto chileno.</p>
<p>En este contexto, el presente estudio busca analizar la relación entre la religiosidad y el apoyo a gobiernos autoritarios en Chile utilizando datos de la Encuesta Social Longitudinal de Chile (ELSOC), Ola 7 (2023). Para ello, se examina si la frecuencia de asistencia a servicios religiosos se asocia con una mayor probabilidad de apoyar o mostrar indiferencia frente a gobiernos autoritarios, considerando además la influencia de variables sociodemográficas y políticas.</p>
<p>En función de lo anterior, la investigación se orienta a responder la siguiente pregunta:</p>
<p><strong>¿Cuál es la relación entre la religiosidad y el apoyo a gobiernos autoritarios en Chile?</strong></p>
<p><strong>Hipótesis</strong></p>
<p>Una mayor frecuencia de asistencia a servicios religiosos se asocia con una mayor probabilidad de manifestar una actitud favorable hacia gobiernos autoritarios.</p>
<p><strong>Objetivo General</strong></p>
<p>Analizar la relación entre la religiosidad y el apoyo a gobiernos autoritarios en la población chilena, utilizando datos de la Encuesta Social Longitudinal de Chile (ELSOC), Ola 7 (2023).</p>
</section>
<section id="metodología" class="level4">
<h4 class="anchored" data-anchor-id="metodología">Metodología</h4>
<p>El presente estudio utiliza datos de la séptima ola del Estudio Longitudinal Social de Chile (ELSOC 2023), desarrollado por el Centro de Estudios de Conflicto y Cohesión Social (COES). La población objetivo corresponde a hombres y mujeres de la muestra original y de refresco residentes en zonas urbanas del país.</p>
</section>
<section id="operacionalización-de-las-variables" class="level4">
<h4 class="anchored" data-anchor-id="operacionalización-de-las-variables">Operacionalización de las variables</h4>
<p>Para capturar los constructos de interés, se procedió en primer lugar a la recodificación de los valores perdidos y respuestas no sustantivas. En particular, las categorías correspondientes a valores no válidos (códigos -999, -888, -777 y -666) en la base de datos original fueron transformadas en valores perdidos (<span class="math inline">\(NA\)</span>) antes de realizar cualquier cálculo, con el fin de evitar sesgos en la estimación de los modelos.</p>
<p>Asimismo, para asegurar la correcta dirección e interpretación teórica de los ítems continuos, la variable de asistencia a rituales religiosos fue invertida de modo que valores más altos reflejen consistentemente una mayor frecuencia de participación. La consistencia interna de la escala multítem fue evaluada mediante el coeficiente Alfa de Cronbach.</p>
<ul>
<li><p><strong>Preferencia por Gobierno Autoritario (Variable Dependiente):</strong> Se construyó como una variable binaria a partir del ítem <code>c25_w07</code> (escala original de 3 categorías que evalúa la preferencia por regímenes políticos). Se recodificó en dos categorías sustantivas: <strong>0 = Preferencia por la democracia</strong> (correspondiente a la opción original “La democracia es preferible a cualquier otra forma de gobierno”) y <strong>1 = Apoyo o indiferencia frente al autoritarismo</strong> (que agrupa las opciones “En algunas circunstancias, un gobierno autoritario puede ser preferible a uno democrático” y “A la gente como uno, nos da lo mismo un régimen democrático que uno no democrático”).</p></li>
<li><p><strong>Sumisión Autoritaria (Predictor 1):</strong> Se construyó a partir de la batería <code>C18</code>, utilizando los ítems <code>c18_05_w07</code>, <code>c18_06_w07</code> y <code>c18_07_w07</code> (escala Likert de 1 a 5, donde 1 representa “Totalmente en desacuerdo” y 5 “Totalmente de acuerdo”), que evalúan la propensión a la obediencia, el respeto a la autoridad y el apego a las normas tradicionales. Los ítems se mantuvieron en su dirección original, de modo que valores más altos indican un mayor nivel de sumisión autoritaria. El índice final fue calculado como el promedio de los tres ítems (<code>rowMeans</code>) y su confiabilidad se reportó mediante el coeficiente Alfa de Cronbach.</p></li>
<li><p><strong>Posición Política (Predictor 2):</strong> Se construyó a partir del ítem de autoubicación ideológica <code>c15_w07</code> (escala original de 0 a 10, donde 0 es “Izquierda” y 10 es “Derecha”). La variable fue recodificada en cuatro categorías categóricas mutuamente excluyentes: <strong>Izquierda</strong> (valores 0 a 3), <strong>Centro</strong> (valores 4 a 6), <strong>Derecha</strong> (valores 7 a 10) y <strong>Sin identificación</strong> (valores 11 y 12, correspondientes a “Ninguno” e “Independiente”), siendo esta última tratada como categoría de respuesta válida para evitar la pérdida masiva de casos.</p></li>
<li><p><strong>Nivel de Estudios (Predictor 3):</strong> Se construyó a partir de la variable <code>m01_w07</code> que registra el máximo nivel educacional alcanzado por el encuestado. Los niveles originales fueron colapsados en tres categorías principales para facilitar la estimación del modelo: <strong>Básica o media</strong> (valores 1 a 5, que abarcan desde educación básica incompleta hasta media técnica o humanística completa), <strong>Superior técnica</strong> (valores 6 y 7, que incluyen carreras técnicas superiores incompletas y completas) y <strong>Superior universitaria</strong> (valores 8 a 10, que agrupa educación universitaria y estudios de postgrado).</p></li>
<li><p><strong>Frecuencia Religiosa (Variable Adicional / Predictor 4):</strong> Se construyó a partir del ítem <code>m39_w07</code>, el cual mide la frecuencia de asistencia a servicios, cultos o rituales religiosos en una escala ordinal de 1 a 7 (donde 1 representa “Varias veces a la semana” y 7 “Nunca o casi nunca”). Para asegurar que valores más altos indiquen mayor involucramiento y facilitar la interpretación de los coeficientes, el ítem fue invertido mediante la fórmula <span class="math inline">\(8 - x\)</span>. De este modo, la escala final varía de 1 a 7, donde valores superiores reflejan una mayor frecuencia acumulada de participación religiosa.</p></li>
</ul>
<ol type="1">
<li>Carga de librerías, datos y selección de variables</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'psych'

The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"ELSOC_Wide_2016_2023.RData"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(elsoc_wide_2016_2023)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>elsoc_wide_2016_2023 <span class="ot">&lt;-</span> elsoc_wide_2016_2023 <span class="sc">%&gt;%</span> <span class="fu">select</span>(c18_05_w07, c18_06_w07, c18_07_w07, m39_w07, c15_w07, c25_w07, m01_w07) <span class="co">#primeras 3 c18 son la escala de sumision autoritaria, y m39 sobre religion, asistencia a cosas religiosas , c15 ideologia politica, c25 aprobacion o no gobierno autoritaria binaria y m01 nuvel educativo, el w07 significa ola7</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="2" type="1">
<li>Limpieza y Tratamiento de Valores Perdidos</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplazar códigos de valores perdidos por NA</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>elsoc_wide_2016_2023 <span class="ot">&lt;-</span> elsoc_wide_2016_2023 <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">everything</span>(),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>      <span class="sc">~</span> <span class="fu">replace</span>(., . <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">777</span>, <span class="sc">-</span><span class="dv">666</span>), <span class="cn">NA</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#revisar si hay variables na</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(elsoc_wide_2016_2023)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   c18_05_w07      c18_06_w07      c18_07_w07       m39_w07     
 Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
 1st Qu.:4.000   1st Qu.:4.000   1st Qu.:4.000   1st Qu.:4.000  
 Median :4.000   Median :4.000   Median :4.000   Median :6.000  
 Mean   :3.976   Mean   :3.873   Mean   :3.816   Mean   :5.172  
 3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:7.000  
 Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :7.000  
 NA's   :1735    NA's   :1724    NA's   :1723    NA's   :2092   
    c15_w07          c25_w07         m01_w07      
 Min.   : 0.000   Min.   :1.000   Min.   : 1.000  
 1st Qu.: 5.000   1st Qu.:1.000   1st Qu.: 4.000  
 Median : 6.000   Median :2.000   Median : 5.000  
 Mean   : 7.454   Mean   :1.875   Mean   : 5.372  
 3rd Qu.:12.000   3rd Qu.:3.000   3rd Qu.: 7.000  
 Max.   :12.000   Max.   :4.000   Max.   :10.000  
 NA's   :1742     NA's   :1756    NA's   :1721    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(elsoc_wide_2016_2023<span class="sc">$</span>c18_05_w07, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5 &lt;NA&gt; 
  50  180  267 1502  713 1735 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(elsoc_wide_2016_2023<span class="sc">$</span>c18_06_w07, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5 &lt;NA&gt; 
  69  222  294 1539  599 1724 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(elsoc_wide_2016_2023<span class="sc">$</span>c18_07_w07, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5 &lt;NA&gt; 
  48  237  372 1577  490 1723 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(elsoc_wide_2016_2023<span class="sc">$</span>c25_w07, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4 &lt;NA&gt; 
1336  504  703  148 1756 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(elsoc_wide_2016_2023<span class="sc">$</span>c15_w07, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1    2    3    4    5    6    7    8    9   10   11   12 &lt;NA&gt; 
 130   48   73  141  173  694  108  109   72   28  167   69  893 1742 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(elsoc_wide_2016_2023<span class="sc">$</span>m01_w07, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10 &lt;NA&gt; 
  23  307  275  322  820   78  363  110  375   53 1721 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(elsoc_wide_2016_2023<span class="sc">$</span>m39_w07, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7 &lt;NA&gt; 
 168  268  126  188  306  277 1022 2092 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chequear variable nueva religion </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(elsoc_wide_2016_2023<span class="sc">$</span>m39_w07)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$label
[1] "Frecuencia de asistencia a servicios religiosos (2023)"

$labels
                          No Responde                               No Sabe 
                                 -999                                  -888 
      Valor perdido por error tecnico Valor perdido por encuesta incompleta 
                                 -777                                  -666 
             Varias veces a la semana                   Una vez a la semana 
                                    1                                     2 
              Dos a tres veces al mes                        Una vez al mes 
                                    3                                     4 
                 Varias veces al anno                       Una vez al anno 
                                    5                                     6 
                   Nunca o casi nunca 
                                    7 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(elsoc_wide_2016_2023<span class="sc">$</span>c18_05_w07)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$label
[1] "Grado de acuerdo: Pais necesita un mandatario fuerte (2023)"

$labels
                          No Responde                               No Sabe 
                                 -999                                  -888 
      Valor perdido por error tecnico Valor perdido por encuesta incompleta 
                                 -777                                  -666 
             Totalmente en desacuerdo                         En desacuerdo 
                                    1                                     2 
       Ni en desacuerdo ni de acuerdo                            De acuerdo 
                                    3                                     4 
                Totalmente de acuerdo 
                                    5 </code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Recodificación</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#recodificacion</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>elsoc_wide_2016_2023 <span class="ot">&lt;-</span> elsoc_wide_2016_2023 <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">posicion_politica =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>      c15_w07 <span class="sc">%in%</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">3</span> <span class="sc">~</span> <span class="st">"Izquierda"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>      c15_w07 <span class="sc">%in%</span> <span class="dv">4</span><span class="sc">:</span><span class="dv">6</span> <span class="sc">~</span> <span class="st">"Centro"</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>      c15_w07 <span class="sc">%in%</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">10</span> <span class="sc">~</span> <span class="st">"Derecha"</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>      c15_w07 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">12</span>) <span class="sc">~</span> <span class="st">"Sin identificación"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">factor</span>(<span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Izquierda"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Centro"</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Derecha"</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Sin identificación"</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>      )),</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">gobierno_autoritario =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>      c25_w07 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>      c25_w07 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>      <span class="fu">factor</span>(<span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Preferencia por democracia"</span>,</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Apoyo explícito o implícito a gobierno autoritario"</span></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>      )),</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">nivel_estudio =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>      m01_w07 <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span> <span class="sc">~</span> <span class="st">"Básica o media"</span>,</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>      m01_w07 <span class="sc">%in%</span> <span class="dv">6</span><span class="sc">:</span><span class="dv">7</span> <span class="sc">~</span> <span class="st">"Superior técnica"</span>,</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>      m01_w07 <span class="sc">%in%</span> <span class="dv">8</span><span class="sc">:</span><span class="dv">10</span> <span class="sc">~</span> <span class="st">"Superior universitaria"</span>,</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>      <span class="fu">factor</span>(<span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Básica o media"</span>,</span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Superior técnica"</span>,</span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Superior universitaria"</span></span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a>      )),</span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">frecuencia_religiosa =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-43"><a href="#cb27-43" aria-hidden="true" tabindex="-1"></a>      m39_w07 <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span> <span class="sc">~</span> <span class="dv">8</span> <span class="sc">-</span> m39_w07,</span>
<span id="cb27-44"><a href="#cb27-44" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb27-45"><a href="#cb27-45" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-46"><a href="#cb27-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-47"><a href="#cb27-47" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="4" type="1">
<li>Escala de sumisión autoritaria y consistencia interna</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear escala de sumisión autoritaria (promedio de los tres ítems)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>elsoc_wide_2016_2023 <span class="ot">&lt;-</span> elsoc_wide_2016_2023 <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sumision_autoritaria =</span> <span class="fu">rowMeans</span>(</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(., c18_05_w07, c18_06_w07, c18_07_w07),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">FALSE</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co">#crear alpha sumision autoritaria</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>alpha_sumision <span class="ot">&lt;-</span> <span class="fu">alpha</span>(</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  elsoc_wide_2016_2023 <span class="sc">%&gt;%</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(c18_05_w07,</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>           c18_06_w07,</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>           c18_07_w07)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>alpha_sumision</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: alpha(x = elsoc_wide_2016_2023 %&gt;% select(c18_05_w07, c18_06_w07, 
    c18_07_w07))

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
      0.82      0.82    0.76       0.6 4.5 0.0047  3.9 0.77     0.56

    95% confidence boundaries 
         lower alpha upper
Feldt     0.81  0.82  0.83
Duhachek  0.81  0.82  0.83

 Reliability if an item is dropped:
           raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
c18_05_w07      0.83      0.83    0.71      0.71 4.9   0.0051    NA  0.71
c18_06_w07      0.69      0.69    0.53      0.53 2.3   0.0092    NA  0.53
c18_07_w07      0.72      0.72    0.56      0.56 2.5   0.0085    NA  0.56

 Item statistics 
              n raw.r std.r r.cor r.drop mean   sd
c18_05_w07 2712  0.81  0.81  0.64   0.59  4.0 0.89
c18_06_w07 2723  0.89  0.88  0.81   0.73  3.9 0.93
c18_07_w07 2724  0.87  0.87  0.79   0.71  3.8 0.89

Non missing response frequency for each item
              1    2    3    4    5 miss
c18_05_w07 0.02 0.07 0.10 0.55 0.26 0.39
c18_06_w07 0.03 0.08 0.11 0.57 0.22 0.39
c18_07_w07 0.02 0.09 0.14 0.58 0.18 0.39</code></pre>
</div>
</div>
</section>
<section id="consistencia-interna-alpha-de-cronbach" class="level4">
<h4 class="anchored" data-anchor-id="consistencia-interna-alpha-de-cronbach">Consistencia interna (Alpha de Cronbach)</h4>
<p>La consistencia interna de la escala fue evaluada mediante el alfa de Cronbach. El resultado obtenido fue <strong>α = 0.82</strong> (IC95%: 0.81–0.83), lo que indica una buena consistencia interna entre los ítems que componen la escala. En consecuencia, puede considerarse una medida confiable para representar el constructo de adhesión a actitudes autoritarias.</p>
<ol start="5" type="1">
<li>preparación de la muestra para modelamiento</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Eliminar casos con datos perdidos en las variables </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>datos_modelo <span class="ot">&lt;-</span> elsoc_wide_2016_2023 <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    gobierno_autoritario,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    sumision_autoritaria,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    posicion_politica,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    nivel_estudio,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    frecuencia_religiosa</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos_modelo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   c18_05_w07      c18_06_w07      c18_07_w07       m39_w07     
 Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
 1st Qu.:4.000   1st Qu.:4.000   1st Qu.:4.000   1st Qu.:4.000  
 Median :4.000   Median :4.000   Median :4.000   Median :6.000  
 Mean   :4.056   Mean   :3.976   Mean   :3.918   Mean   :5.197  
 3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:7.000  
 Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :7.000  
    c15_w07          c25_w07         m01_w07                posicion_politica
 Min.   : 0.000   Min.   :1.000   Min.   : 1.000   Izquierda         :278    
 1st Qu.: 5.000   1st Qu.:1.000   1st Qu.: 4.000   Centro            :817    
 Median : 6.000   Median :1.000   Median : 5.000   Derecha           :327    
 Mean   : 7.511   Mean   :1.782   Mean   : 5.235   Sin identificación:756    
 3rd Qu.:12.000   3rd Qu.:3.000   3rd Qu.: 7.000                             
 Max.   :12.000   Max.   :3.000   Max.   :10.000                             
                                         gobierno_autoritario
 Preferencia por democracia                        :1099     
 Apoyo explícito o implícito a gobierno autoritario:1079     
                                                             
                                                             
                                                             
                                                             
                nivel_estudio  frecuencia_religiosa sumision_autoritaria
 Básica o media        :1456   Min.   :1.000        Min.   :1.000       
 Superior técnica      : 359   1st Qu.:1.000        1st Qu.:3.667       
 Superior universitaria: 363   Median :2.000        Median :4.000       
                               Mean   :2.803        Mean   :3.983       
                               3rd Qu.:4.000        3rd Qu.:4.333       
                               Max.   :7.000        Max.   :5.000       </code></pre>
</div>
</div>
</section>
</section>
<section id="estimación-de-modelos-de-regresión-logística-binaria" class="level3">
<h3 class="anchored" data-anchor-id="estimación-de-modelos-de-regresión-logística-binaria">Estimación de Modelos de Regresión Logística Binaria</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#glm modelo base</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>modelo_base <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  gobierno_autoritario <span class="sc">~</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    sumision_autoritaria <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    posicion_politica <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    nivel_estudio,</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> datos_modelo,</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_base)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = gobierno_autoritario ~ sumision_autoritaria + posicion_politica + 
    nivel_estudio, family = binomial(link = "logit"), data = datos_modelo)

Coefficients:
                                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                         -3.15194    0.33424  -9.430  &lt; 2e-16 ***
sumision_autoritaria                 0.66184    0.07736   8.556  &lt; 2e-16 ***
posicion_politicaCentro              0.57989    0.15526   3.735 0.000188 ***
posicion_politicaDerecha             1.01020    0.18360   5.502 3.75e-08 ***
posicion_politicaSin identificación  0.76801    0.15597   4.924 8.47e-07 ***
nivel_estudioSuperior técnica       -0.29581    0.12557  -2.356 0.018490 *  
nivel_estudioSuperior universitaria -0.68876    0.13490  -5.106 3.29e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3019.2  on 2177  degrees of freedom
Residual deviance: 2806.3  on 2171  degrees of freedom
AIC: 2820.3

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<section id="section-1" class="level4">
<h4 class="anchored" data-anchor-id="section-1"></h4>
</section>
</section>
<section id="modelo-1-variables-sociodemográficas-y-actitudinales" class="level3">
<h3 class="anchored" data-anchor-id="modelo-1-variables-sociodemográficas-y-actitudinales">Modelo 1: Variables sociodemográficas y actitudinales</h3>
<p>El primer modelo de regresión logística tuvo como objetivo estimar la probabilidad de manifestar apoyo explícito o implícito a un gobierno autoritario a partir de la sumisión autoritaria, la posición política y el nivel educativo.</p>
<p>Los resultados muestran que la <strong>sumisión autoritaria</strong> presenta una asociación positiva y estadísticamente significativa con el apoyo a gobiernos autoritarios (β = 0.662; <em>p</em> &lt; 0.001). Esto indica que, a medida que aumenta la adhesión a actitudes de obediencia y respeto hacia la autoridad, también aumenta la probabilidad de manifestar apoyo o indiferencia frente a un gobierno autoritario.</p>
<p>En relación con la <strong>posición política</strong>, y tomando como categoría de referencia a quienes se identifican con la izquierda, las personas que se ubican en el <strong>centro</strong>, la <strong>derecha</strong> y quienes declaran <strong>no tener identificación política</strong> presentan una mayor probabilidad de apoyar un gobierno autoritario. Todas estas asociaciones resultan estadísticamente significativas (<em>p</em> &lt; 0.001), siendo la categoría de derecha la que exhibe el mayor efecto positivo.</p>
<p>Respecto al <strong>nivel educativo</strong>, tanto quienes poseen educación superior técnica como quienes cuentan con educación superior universitaria muestran una menor probabilidad de apoyar un gobierno autoritario en comparación con quienes poseen educación básica o media. Ambos coeficientes son negativos y estadísticamente significativos, siendo el efecto más pronunciado entre quienes poseen educación universitaria.</p>
<p>En conjunto, el modelo evidencia que las actitudes de sumisión autoritaria y la posición política constituyen predictores relevantes del apoyo a gobiernos autoritarios, mientras que un mayor nivel educativo se asocia con una menor predisposición hacia este tipo de preferencias políticas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#modelo ampliado</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>modelo_ampliado <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  gobierno_autoritario <span class="sc">~</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    sumision_autoritaria <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    posicion_politica <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    nivel_estudio <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    frecuencia_religiosa,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> datos_modelo,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_ampliado)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = gobierno_autoritario ~ sumision_autoritaria + posicion_politica + 
    nivel_estudio + frecuencia_religiosa, family = binomial(link = "logit"), 
    data = datos_modelo)

Coefficients:
                                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                         -3.123205   0.340457  -9.174  &lt; 2e-16 ***
sumision_autoritaria                 0.661603   0.077332   8.555  &lt; 2e-16 ***
posicion_politicaCentro              0.579146   0.155258   3.730 0.000191 ***
posicion_politicaDerecha             1.012029   0.183658   5.510 3.58e-08 ***
posicion_politicaSin identificación  0.767119   0.155976   4.918 8.74e-07 ***
nivel_estudioSuperior técnica       -0.299297   0.125834  -2.379 0.017383 *  
nivel_estudioSuperior universitaria -0.688943   0.134882  -5.108 3.26e-07 ***
frecuencia_religiosa                -0.009525   0.021908  -0.435 0.663713    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3019.2  on 2177  degrees of freedom
Residual deviance: 2806.1  on 2170  degrees of freedom
AIC: 2822.1

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
<section id="modelo-2-incorporación-de-la-frecuencia-religiosa" class="level3">
<h3 class="anchored" data-anchor-id="modelo-2-incorporación-de-la-frecuencia-religiosa">Modelo 2: Incorporación de la frecuencia religiosa</h3>
<p>El segundo modelo incorpora la <strong>frecuencia de asistencia a servicios religiosos</strong> como predictor adicional, con el propósito de evaluar si la religiosidad contribuye a explicar la probabilidad de apoyar un gobierno autoritario una vez controladas las variables incluidas en el modelo base.</p>
<p>Los resultados muestran que la <strong>sumisión autoritaria</strong> mantiene una asociación positiva y estadísticamente significativa con el apoyo a gobiernos autoritarios (β = 0.662; <em>p</em> &lt; 0.001). Del mismo modo, la <strong>posición política</strong> continúa mostrando diferencias significativas respecto de la categoría de referencia (izquierda), observándose una mayor probabilidad de apoyo entre quienes se identifican con el centro, la derecha y quienes no presentan identificación política.</p>
<p>Asimismo, el <strong>nivel educativo</strong> conserva el mismo patrón observado en el modelo anterior. Tanto la educación superior técnica como la educación superior universitaria se asocian con una menor probabilidad de apoyar un gobierno autoritario en comparación con quienes poseen educación básica o media, manteniendo asociaciones estadísticamente significativas.</p>
<p>En contraste, la <strong>frecuencia de asistencia a servicios religiosos</strong> no presenta una asociación estadísticamente significativa con el apoyo a gobiernos autoritarios (β = -0.010; <em>p</em> = 0.664). Esto indica que, una vez controladas las variables actitudinales, políticas y educativas incluidas en el modelo, la frecuencia de participación religiosa no aporta evidencia suficiente para explicar diferencias en la probabilidad de apoyar un gobierno autoritario.</p>
<p>En términos generales, la incorporación de la variable de religiosidad no modifica sustancialmente el comportamiento ni la significancia de los predictores del modelo base, lo que sugiere que la asociación entre religiosidad y apoyo a gobiernos autoritarios no encuentra respaldo empírico en los datos analizados.</p>
<p><code>pero</code></p>
</section>
<section id="estimación-y-diagnostico-del-modelo" class="level3">
<h3 class="anchored" data-anchor-id="estimación-y-diagnostico-del-modelo">Estimación y diagnostico del modelo</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#odds rattio</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(modelo_base))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        (Intercept)                sumision_autoritaria 
                         0.04276895                          1.93834689 
            posicion_politicaCentro            posicion_politicaDerecha 
                         1.78583362                          2.74615561 
posicion_politicaSin identificación       nivel_estudioSuperior técnica 
                         2.15547031                          0.74393188 
nivel_estudioSuperior universitaria 
                         0.50219591 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(modelo_ampliado))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        (Intercept)                sumision_autoritaria 
                         0.04401585                          1.93789724 
            posicion_politicaCentro            posicion_politicaDerecha 
                         1.78451333                          2.75117781 
posicion_politicaSin identificación       nivel_estudioSuperior técnica 
                         2.15355320                          0.74133940 
nivel_estudioSuperior universitaria                frecuencia_religiosa 
                         0.50210635                          0.99051979 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#intervalo de confianza en or</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(modelo_base))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                        2.5 %    97.5 %
(Intercept)                         0.0220118 0.0816430
sumision_autoritaria                1.6685091 2.2598860
posicion_politicaCentro             1.3205877 2.4285127
posicion_politicaDerecha            1.9208886 3.9469833
posicion_politicaSin identificación 1.5916553 2.9350410
nivel_estudioSuperior técnica       0.5813209 0.9513072
nivel_estudioSuperior universitaria 0.3847667 0.6531645</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(modelo_ampliado))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         2.5 %    97.5 %
(Intercept)                         0.02237721 0.0850461
sumision_autoritaria                1.66820877 2.2592511
posicion_politicaCentro             1.31963151 2.4266892
posicion_politicaDerecha            1.92416822 3.9546981
posicion_politicaSin identificación 1.59021198 2.9324844
nivel_estudioSuperior técnica       0.57899561 0.9484730
nivel_estudioSuperior universitaria 0.38471169 0.6530252
frecuencia_religiosa                0.94887133 1.0339903</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#BIC</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(modelo_base)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2860.124</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(modelo_ampliado)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2867.621</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#pseudo r al cuadrado</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pscl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Classes and Methods for R originally developed in the
Political Science Computational Laboratory
Department of Political Science
Stanford University (2002-2015),
by and under the direction of Simon Jackman.
hurdle and zeroinfl functions by Achim Zeileis.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(modelo_base)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          llh       llhNull            G2      McFadden          r2ML 
-1.403160e+03 -1.509583e+03  2.128447e+02  7.049787e-02  9.310160e-02 
         r2CU 
 1.241390e-01 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(modelo_ampliado)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitting null model for pseudo-r2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          llh       llhNull            G2      McFadden          r2ML 
-1.403066e+03 -1.509583e+03  2.130338e+02  7.056048e-02  9.318031e-02 
         r2CU 
 1.242439e-01 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#VIF</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:psych':

    logit</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_base)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         GVIF Df GVIF^(1/(2*Df))
sumision_autoritaria 1.075803  1        1.037209
posicion_politica    1.101357  3        1.016221
nivel_estudio        1.097009  2        1.023417</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_ampliado)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         GVIF Df GVIF^(1/(2*Df))
sumision_autoritaria 1.075888  1        1.037250
posicion_politica    1.103904  3        1.016612
nivel_estudio        1.101706  2        1.024510
frecuencia_religiosa 1.006179  1        1.003085</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Cook</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cooks.distance</span>(modelo_base))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-final-estadística-CEA_KENNEDY_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">cooks.distance</span>(modelo_ampliado))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-final-estadística-CEA_KENNEDY_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#efectos marginales</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(modelo_base)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                 Term                                Contrast Estimate
 nivel_estudio        Superior técnica - Básica o media        -0.0686
 nivel_estudio        Superior universitaria - Básica o media  -0.1576
 posicion_politica    Centro - Izquierda                        0.1312
 posicion_politica    Derecha - Izquierda                       0.2305
 posicion_politica    Sin identificación - Izquierda            0.1749
 sumision_autoritaria dY/dX                                     0.1502
 Std. Error     z Pr(&gt;|z|)    S   2.5 %  97.5 %
     0.0291 -2.36   0.0185  5.8 -0.1257 -0.0115
     0.0301 -5.24   &lt;0.001 22.5 -0.2166 -0.0986
     0.0340  3.85   &lt;0.001 13.1  0.0645  0.1979
     0.0406  5.68   &lt;0.001 26.2  0.1510  0.3100
     0.0343  5.10   &lt;0.001 21.5  0.1077  0.2422
     0.0165  9.12   &lt;0.001 63.6  0.1179  0.1825

Type: response</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(modelo_ampliado)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                 Term                                Contrast Estimate
 frecuencia_religiosa dY/dX                                   -0.00216
 nivel_estudio        Superior técnica - Básica o media       -0.06939
 nivel_estudio        Superior universitaria - Básica o media -0.15765
 posicion_politica    Centro - Izquierda                       0.13098
 posicion_politica    Derecha - Izquierda                      0.23089
 posicion_politica    Sin identificación - Izquierda           0.17471
 sumision_autoritaria dY/dX                                    0.15014
 Std. Error      z Pr(&gt;|z|)    S   2.5 %   97.5 %
    0.00497 -0.435   0.6639  0.6 -0.0119  0.00759
    0.02917 -2.379   0.0174  5.8 -0.1266 -0.01222
    0.03010 -5.238   &lt;0.001 22.6 -0.2166 -0.09866
    0.03403  3.849   &lt;0.001 13.0  0.0643  0.19767
    0.04058  5.690   &lt;0.001 26.2  0.1513  0.31042
    0.03431  5.092   &lt;0.001 21.4  0.1075  0.24196
    0.01645  9.125   &lt;0.001 63.6  0.1179  0.18239

Type: response</code></pre>
</div>
</div>
</section>
<section id="comparación-de-modelos-e-interpretación-general" class="level3">
<h3 class="anchored" data-anchor-id="comparación-de-modelos-e-interpretación-general">Comparación de modelos e interpretación general</h3>
<p>La comparación entre ambos modelos muestra que la incorporación de la <strong>frecuencia de asistencia a servicios religiosos</strong> no mejora el desempeño explicativo del modelo. Si bien el pseudo R² de McFadden aumenta levemente de <strong>0.0705</strong> a <strong>0.0706</strong>, esta diferencia es prácticamente nula. Del mismo modo, el <strong>AIC</strong> aumenta de <strong>2820.3</strong> en el modelo base a <strong>2822.1</strong> en el modelo ampliado, mientras que el <strong>BIC</strong> pasa de <strong>2860.1</strong> a <strong>2867.6</strong>, indicando un ajuste ligeramente menos favorable tras incorporar la variable de religiosidad.</p>
<p>Los <strong>odds ratio</strong> muestran que la <strong>sumisión autoritaria</strong> constituye el predictor de mayor interés teórico, incrementando aproximadamente en un <strong>94%</strong> las probabilidades de apoyar un gobierno autoritario por cada punto adicional en la escala (OR = 1.94). Asimismo, en comparación con quienes se identifican con la izquierda, las personas que se ubican en el <strong>centro</strong> (OR = 1.78), la <strong>derecha</strong> (OR = 2.75) y quienes <strong>no presentan identificación política</strong> (OR = 2.15) exhiben mayores probabilidades de manifestar apoyo a un gobierno autoritario. En contraste, poseer <strong>educación superior técnica</strong> (OR = 0.74) o <strong>educación superior universitaria</strong> (OR = 0.50) se asocia con una menor probabilidad de respaldar este tipo de gobierno.</p>
<p>Por su parte, la <strong>frecuencia de asistencia a servicios religiosos</strong> presenta un <strong>OR = 0.99</strong>, un intervalo de confianza que incluye el valor 1 y un coeficiente no significativo, lo que indica que esta variable no contribuye a explicar el apoyo a gobiernos autoritarios una vez controladas las demás variables del modelo. Este resultado debe interpretarse considerando el enfoque teórico de la investigación. La frecuencia de asistencia no fue utilizada para medir la religiosidad entendida como creencia o espiritualidad individual, sino como un <strong>indicador de la dimensión práctica de la religiosidad</strong>, es decir, de la participación en espacios donde históricamente se transmiten normas, valores tradicionales y formas de relación con la autoridad. Bajo esta perspectiva, la hipótesis suponía que una mayor participación en dichos espacios podría asociarse con una mayor predisposición hacia actitudes favorables al autoritarismo. Sin embargo, los resultados obtenidos no entregan evidencia empírica que respalde esa asociación.</p>
<p>Respecto a los diagnósticos del modelo, los valores del <strong>GVIF ajustado</strong> se mantienen cercanos a <strong>1</strong> para todas las variables, descartando problemas de multicolinealidad. Asimismo, la inspección de la distancia de Cook no evidencia observaciones con influencia desproporcionada sobre las estimaciones, lo que respalda la estabilidad de los coeficientes obtenidos.</p>
<p>En conjunto, los resultados indican que el apoyo a gobiernos autoritarios se encuentra asociado principalmente con la <strong>sumisión autoritaria</strong>, la <strong>posición política</strong> y el <strong>nivel educativo</strong>, mientras que la frecuencia de asistencia a servicios religiosos no constituye un predictor significativo una vez controlados estos factores. En consecuencia, la evidencia obtenida <strong>no permite respaldar la hipótesis de investigación</strong>, sugiriendo que la participación en prácticas religiosas, entendida como una aproximación a la dimensión cultural y normativa de la religiosidad, no explica por sí sola una mayor probabilidad de apoyar gobiernos autoritarios en la muestra analizada.</p>
</section>
<section id="conclusión" class="level3">
<h3 class="anchored" data-anchor-id="conclusión">Conclusión</h3>
<p>El presente estudio tuvo como objetivo analizar la relación entre la religiosidad y el apoyo a gobiernos autoritarios en Chile utilizando datos de la Encuesta Social Longitudinal de Chile (ELSOC), Ola 7 (2023). Los resultados muestran que la <strong>sumisión autoritaria</strong>, la <strong>posición política</strong> y el <strong>nivel educativo</strong> constituyen predictores significativos del apoyo a gobiernos autoritarios. En cambio, la <strong>frecuencia de asistencia a servicios religiosos</strong> no presentó una asociación estadísticamente significativa una vez controladas las demás variables del modelo.</p>
<p>Estos hallazgos indican que la hipótesis planteada no encuentra respaldo empírico en la muestra analizada. En consecuencia, la evidencia obtenida no permite sostener que una mayor frecuencia de participación en actividades religiosas se asocie con una mayor probabilidad de apoyar gobiernos autoritarios en el contexto chileno.</p>
<p>Es importante señalar que la variable utilizada no buscó medir la religiosidad como una experiencia de fe o espiritualidad individual. La <strong>frecuencia de asistencia a servicios religiosos</strong> fue entendida como una aproximación a la dimensión práctica de la religiosidad, es decir, a la participación en espacios donde históricamente se transmiten normas, valores tradicionales y formas de relación con la autoridad. Desde esta perspectiva, la expectativa teórica era que una mayor participación pudiera reflejar una mayor internalización de valores asociados a la obediencia, el orden y el convencionalismo. Sin embargo, los resultados sugieren que dicha dimensión práctica, por sí sola, no constituye un factor explicativo del apoyo a gobiernos autoritarios cuando se consideran simultáneamente variables actitudinales, políticas y educativas.</p>
</section>
<section id="bibliografía" class="level3">
<h3 class="anchored" data-anchor-id="bibliografía">Bibliografía</h3>
<p>Parzen, H. (1951). [Review of <em>The Authoritarian Personality</em>, by T. W. Adorno, E. Frenkelbrunswik, D. J. Levinson, &amp; R. N. Sanford]. <em>Publications of the American Jewish Historical Society</em>, <em>41</em>(1), 97–104. <a href="https://0h10j3zqu-y-https-www-jstor-org.itmsp.museknowledge.com/stable/43059813?seq=3" class="uri">https://0h10j3zqu-y-https-www-jstor-org.itmsp.museknowledge.com/stable/43059813?seq=3</a></p>
<p>Glock, C. Y. (1962). ON THE STUDY OF RELIGIOUS COMMITMENT.&nbsp;<em>Religious Education</em>,&nbsp;<em>57</em>(sup4), 98–110. <a href="https://doi.org/10.1080/003440862057S407" class="uri">https://doi.org/10.1080/003440862057S407</a></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>